import { Ubuntu } from 'next/font/google'
 
const ubuntu = Ubuntu({
  weight: '300',
  subsets: ['latin'],
  display: 'swap',
})
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
